### ISSUE TITLE
jsp - javax.servlet.ServletException cannot be resolved to a type

### ISSUE THREAD

**Issue by ValchanOficial** [ValchanOficial/java-intermediate#2]
https://stackoverflow.com/questions/15781902/javax-servlet-servletexception-cannot-be-resolved-to-a-type-in-spring-web-app

In Eclipse select your project → then go to properties → click on Targeted Runtimes → now you must select a check box next to the server you are using to run current project → click Apply → then click OK button.

**Comment by Shaik-Luqmaan** [comment]
Thank You so much !
